// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_dup
CharacterVector test_dup(CharacterVector x, IntegerVector i);
RcppExport SEXP RcppStringiExample_test_dup(SEXP xSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    __result = Rcpp::wrap(test_dup(x, i));
    return __result;
END_RCPP
}
// test_paste
CharacterVector test_paste(CharacterVector x);
RcppExport SEXP RcppStringiExample_test_paste(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(test_paste(x));
    return __result;
END_RCPP
}
