# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_dup <- function(x, i) {
    .Call('RcppStringiExample_test_dup', PACKAGE = 'RcppStringiExample', x, i)
}

test_paste <- function(x) {
    .Call('RcppStringiExample_test_paste', PACKAGE = 'RcppStringiExample', x)
}

