# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Duplicates a given string
#' @param x a character vector
#' @param i an integer vector
#' @return a character vector
#'
#' @examples
#' test_dup("A", 1)
#'
#' @export
test_dup <- function(x, i) {
    .Call('ExampleRcppStringi_test_dup', PACKAGE = 'ExampleRcppStringi', x, i)
}

#' Concatenates all strings into a single one
#' @param x a character vector
#' @return a character vector
#'
#' @examples
#' test_paste(letters)
#'
#' @export
test_paste <- function(x) {
    .Call('ExampleRcppStringi_test_paste', PACKAGE = 'ExampleRcppStringi', x)
}

